version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.161.130
      KAFKA_CREATE_TOPICS: "lianyu-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always
